version: '3.5'
services:
  minio-kes:
    image: minio/kes:latest
    container_name: minio-kes
    restart: always
    volumes:
      - ./kes:/root/
    environment:
      - KES_SERVER=https://127.0.0.1:7373
      - KES_CLIENT_KEY=/root/client.key
      - KES_CLIENT_CERT=/root/client.crt
    ports:
      - "7373:7373"
    command: server --config=/root/config.yml --auth=off 